### PR TITLE
Chore: added ci-cd

### PR DESCRIPTION
**Pull request by ernesteNtezirizaza**
## CI/CD PR

Configure a continuous integration pipeline using GitHub Actions.

It contains the following acceptance criteria:

1. Configured Testing environment with Mocha, Chai and Sinon to ensure all functionalities are tested before deployment.

2. GitHub Actions is configured as a continuous integration service to build and test the app.

3. GitHub Actions badge has been added to your repo.

## How to manually test it 

Run **npm test** to see if all your tests are working as expected.

image

image

To check if the GitHub Actions badge has been added to your repo, go to **README** File.

image

### CODE REVIEW

**Review by thepatrickniyo — APPROVED** [review]
LGTM, good work

**Comment by ernesteNtezirizaza** [comment]
> LGTM, good work

Thank you, Mr. Patrick.

**Comment by claranceliberi** [comment]
I advise everyone to install Code Climate Extension to get the most out of code climate functionalities on the GitHub platform. 

https://chrome.google.com/webstore/detail/code-climate/phgahogocbnfilkegjdpohgkkjgahjgk

**Review by thepatrickniyo — COMMENTED** [review]
Resolve the conflicts and we go

**Pull request closed without merging**
