### PR TITLE
Chore/support multiple languages

### PR DESCRIPTION
**Pull request by IrakozeLoraine**
## Support Multiple Languages PR

Supporting multiple languages

It contains the following acceptance criteria:

1. Users should be able to change/select a language of their choice.

2. The site contents are presented in the newly set language.

3. At least, two languages are supported (English and Kinyarwanda).

## How to manually test it

1. Run **npm start** to start the server.

2. Go to the browser and visit the URL: localhost:[port you are running on/5000]/welcome

3. There you will find a response demonstrating information in both English and Kinyarwanda.
Screenshot 2023-03-15 234026

4. To change the information you present to users according to a certain language:
- Go to  **src/config/languages/en.js** for translated words in English or **src/config/language/rw.js** for translated words in Kinyarwanda in a format like this:
Screenshot 2023-03-15 234525

- Next, go to the route that you want to change in a new language and call the function **locales(key_word_to_translate, language_to_translate_to_(rw_by_default)).
Screenshot 2023-03-15 234026

The site contents will then be presented according to the language desired.

### CODE REVIEW

**Review by thepatrickniyo — APPROVED** [review]
LGTM

**Review by Cyebukayire — APPROVED** [review]

**Comment by aimelyse** [comment]
Good to Go

**Review by aimelyse — APPROVED** [review]
Good to go

**Review by ernesteNtezirizaza — APPROVED** [review]
Ready to go!!!!

**Review by TuyizeeAnastase — CHANGES_REQUESTED** [review]
Can you add PR description and how can be manually tested?  refer to this [engineering playbook](https://github.com/atlp-rwanda/rca-phantom-team1-bn/pull/7) or check repo [#7](https://github.com/atlp-rwanda/rca-phantom-team1-bn/pull/7)

**Comment by IrakozeLoraine** [comment]
> moved to PR description

**Review by TuyizeeAnastase — APPROVED** [review]

**Pull request merged**
